menu:
- {name: 'Projects', url: '/projects'}
- {name: 'Publications', url: '/publications'}
- {name: 'Blog', url: '/blog'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

projects:
- {title: 'Effect of dislocations on phase transformation', 
   description: 'In this project, our aim is to discover the 
   effect of dislocations in phase separation, nucleation and precipitate
   dissolution in binary systems. Solutes in alloys have a strain 
   field around them due to the size difference between the atoms. When 
   solutes encounter a dislocation'} 

social:
- {icon: 'github', link: 'https://github.com/arjunvarmar'}
- {icon: 'twitter', link: 'https://twitter.com/ajnvma/'}
  #- {icon: 'instagram', link: 'https://www.instagram.com/arjun_varma_r/'}
- {icon: 'linkedin', link: 'https://in.linkedin.com/in/arjun-varma-r-a5037888?trk=people-guest_people_search-card'}

contacts:
- {name: 'Arjun Varma R.', 
   title: 'PhD candidate', 
   department: 'Metallurgical Engineering and Materials Scienve', 
   institution: 'Indian Institute of Technology Bombay', 
   institution_address: 'Powai 400076, Maharashtra, India', 
   email: 'arjun-dot-varma-dot-r-at-gmail-dot-com', 
   office: 'Materials and Process Modelling Lab', 
   image: 'assets/img/contact.jpg'}
