menu:
- {name: 'Projects', url: '/projects'}
- {name: 'Publications', url: '/publications'}
- {name: 'Blog', url: '/blog'}
- {name: 'CV', url: '/cv'}
- {name: 'Gallery', url: '/gallery'}

#projects:

blog:

social:
- {icon: 'github', link: 'https://github.com/arjunvarmar'}
- {icon: 'twitter', link: 'https://twitter.com/ajnvma/'}
  #- {icon: 'instagram', link: 'https://www.instagram.com/arjun_varma_r/'}
- {icon: 'linkedin', link: 'https://in.linkedin.com/in/arjun-varma-r-a5037888?trk=people-guest_people_search-card'}
