menu:
- {name: 'Projects', url: '/projects'}
- {name: 'Publications', url: '/publications'}
- {name: 'Blog', url: '/blog'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

projects:
- {title: 'Dislocation assisted phase transformation', description: 'In this project, we are interested in studying the effect of dislocations on phase transformation.'}
- {title: 'Surface diffusion enhanced break-up of nanowire junctions', description: 'blah blah blah'} 
- {title: 'Electron phonon interaction energy component and its influence in determining the stability order in group IV semiconductor polytypes', description: 'blah blah blah'} 

social:
- {icon: 'github', link: 'https://github.com/arjunvarmar'}
- {icon: 'twitter', link: 'https://twitter.com/ajnvma/'}
  #- {icon: 'instagram', link: 'https://www.instagram.com/arjun_varma_r/'}
- {icon: 'linkedin', link: 'https://in.linkedin.com/in/arjun-varma-r-a5037888?trk=people-guest_people_search-card'}

contacts:
- {name: 'Arjun Varma R.', 
   title: 'PhD candidate', 
   department: 'Metallurgical Engineering and Materials Scienve', 
   institution: 'Indian Institute of Technology Bombay', 
   institution_address: 'Powai 400076, Maharashtra, India', 
   email: 'arjun-dot-varma-dot-r-at-gmail-dot-com', 
   office: 'Materials and Process Modelling Lab', 
   image: 'assets/img/contact.jpg'}
